{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5045cd54-55d8-463b-8b96-7b750a8fbb02",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0bd80072-5169-40d8-a145-8b1d9370bf2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "import torch\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "from torchvision import transforms\n",
    "import numpy as np\n",
    "import os\n",
    "import torch\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "930d08f2-21cd-420e-92c1-e2eda2ace859",
   "metadata": {},
   "outputs": [],
   "source": [
    "def getListOfFiles(dirName):\n",
    "    # create a list of file and sub directories \n",
    "    # names in the given directory \n",
    "    listOfFile = os.listdir(dirName)\n",
    "    allFiles = list()\n",
    "    # Iterate over all the entries\n",
    "    for entry in listOfFile:\n",
    "        # Create full path\n",
    "        fullPath = os.path.join(dirName, entry)\n",
    "        # If entry is a directory then get the list of files in this directory \n",
    "        if os.path.isdir(fullPath):\n",
    "            allFiles = allFiles + getListOfFiles(fullPath)\n",
    "        else:\n",
    "            allFiles.append(fullPath)\n",
    "                \n",
    "    return allFiles"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fd7de148-cd67-4a09-a395-b44b35101c25",
   "metadata": {},
   "outputs": [],
   "source": [
    "def tensor_to_image(tensor):\n",
    "    tensor = tensor*255\n",
    "    tensor = np.array(tensor, dtype=np.uint8)\n",
    "    if np.ndim(tensor)>3:\n",
    "        assert tensor.shape[0] == 1\n",
    "        tensor = tensor[0]\n",
    "    return Image.fromarray(tensor)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "aef60720-6227-4f5a-8c96-d6198841faf5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using cache found in /Users/mitchellslapik/.cache/torch/hub/pytorch_vision_v0.10.0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "AlexNet(\n",
       "  (features): Sequential(\n",
       "    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))\n",
       "    (1): ReLU(inplace=True)\n",
       "    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))\n",
       "    (4): ReLU(inplace=True)\n",
       "    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (7): ReLU(inplace=True)\n",
       "    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (9): ReLU(inplace=True)\n",
       "    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (11): ReLU(inplace=True)\n",
       "    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "  )\n",
       "  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))\n",
       "  (classifier): Sequential(\n",
       "    (0): Dropout(p=0.5, inplace=False)\n",
       "    (1): Linear(in_features=9216, out_features=4096, bias=True)\n",
       "    (2): ReLU(inplace=True)\n",
       "    (3): Dropout(p=0.5, inplace=False)\n",
       "    (4): Linear(in_features=4096, out_features=4096, bias=True)\n",
       "    (5): ReLU(inplace=True)\n",
       "    (6): Linear(in_features=4096, out_features=1000, bias=True)\n",
       "  )\n",
       ")"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model = torch.hub.load('pytorch/vision:v0.10.0', 'alexnet', pretrained=True)\n",
    "model.eval()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "87c5ffd9-3779-4ccb-adfa-e1fb153a12d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n",
      "10\n",
      "11\n",
      "12\n",
      "13\n"
     ]
    }
   ],
   "source": [
    "path = '/Users/mitchellslapik/Documents/ml fun/art data'\n",
    "\n",
    "subfolders = os.listdir(path)\n",
    "\n",
    "subfolders.remove('.DS_Store')\n",
    "\n",
    "preprocess = transforms.Compose([\n",
    "    transforms.Resize(30),\n",
    "    transforms.CenterCrop(28),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize((0.5), (0.5))\n",
    "    #transforms.Grayscale(num_output_channels=1)\n",
    "    ])\n",
    "\n",
    "from PIL import ImageFile\n",
    "ImageFile.LOAD_TRUNCATED_IMAGES = True\n",
    "\n",
    "picturedictionary = dict()\n",
    "picturedictionary['train'] = dict()\n",
    "picturedictionary['test'] = dict()\n",
    "\n",
    "\n",
    "for subfolder in range(len(subfolders)):\n",
    "    \n",
    "    print(subfolder)\n",
    "    \n",
    "    count = 0\n",
    "\n",
    "    path = '/Users/mitchellslapik/Documents/ml fun/art data/' + subfolders[subfolder] + '/'\n",
    "\n",
    "    directory_contents = [_ for _ in os.listdir(path) if _.endswith('.jpg')]\n",
    "    \n",
    "    for n in range(1100):#range(len(directory_contents)):\n",
    "        \n",
    "        file_name = directory_contents[n]\n",
    "        \n",
    "        input_image = Image.open('art data/' + subfolders[subfolder] + '/' + file_name).convert('L')\n",
    "        \n",
    "        preprocessed = preprocess(input_image)\n",
    "        \n",
    "        adddimension = preprocessed[None, :]\n",
    "        \n",
    "        if count == 0:\n",
    "            \n",
    "            genre = adddimension\n",
    "            \n",
    "        else:\n",
    "        \n",
    "            genre = torch.concat((genre, adddimension), axis = 0)\n",
    "            \n",
    "                  \n",
    "        count =+ 1\n",
    "        \n",
    "    numberofsamples = genre.shape[0]\n",
    "    \n",
    "    split = round(numberofsamples/11)\n",
    "        \n",
    "    trainsamples = random.sample(range(numberofsamples), split)\n",
    "    \n",
    "    testsamples = list(set(range(numberofsamples))-set(trainsamples))\n",
    "        \n",
    "    picturedictionary['train'][subfolder] = genre[trainsamples, :, :, :]\n",
    "    picturedictionary['test'][subfolder] = genre[testsamples, :, :, :]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30ca36fb-ba33-4703-8987-8b66b144c22d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 347\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/3188906972.py\", line 3, in <module>\n",
      "    plt.imshow(picturedictionary['train'][1].detach().numpy())\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/matplotlib/_api/__init__.py\", line 223, in __getattr__\n",
      "    f\"module {cls.__module__!r} has no attribute {name!r}\")\n",
      "AttributeError: module 'matplotlib' has no attribute 'imshow'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/3188906972.py\", line 3, in <module>\n",
      "    plt.imshow(picturedictionary['train'][1].detach().numpy())\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/matplotlib/_api/__init__.py\", line 223, in __getattr__\n",
      "    f\"module {cls.__module__!r} has no attribute {name!r}\")\n",
      "AttributeError: module 'matplotlib' has no attribute 'imshow'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/3188906972.py\", line 3, in <module>\n",
      "    plt.imshow(picturedictionary['train'][1].detach().numpy())\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/matplotlib/_api/__init__.py\", line 223, in __getattr__\n",
      "    f\"module {cls.__module__!r} has no attribute {name!r}\")\n",
      "AttributeError: module 'matplotlib' has no attribute 'imshow'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n"
     ]
    }
   ],
   "source": [
    "import matplotlib as plt\n",
    "\n",
    "plt.imshow(picturedictionary['train'][1].detach().numpy())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7cca1f1f-5a4a-4ba9-99af-37e204d6ff97",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 350\n",
      "Loss is :2.3025808334350586\n",
      "At step 0:\n",
      "Training Loss is 2.3025808334350586\n",
      "Training Accuracy is 0.15625\n",
      "Testing Accuracy is 0.1\n",
      "Loss is :2.3025851249694824\n",
      "At step 100:\n",
      "Training Loss is 2.3025851249694824\n",
      "Training Accuracy is 0.125\n",
      "Testing Accuracy is 0.1\n",
      "Loss is :2.3025851249694824\n",
      "At step 200:\n",
      "Training Loss is 2.3025851249694824\n",
      "Training Accuracy is 0.0625\n",
      "Testing Accuracy is 0.1\n",
      "Loss is :2.3025851249694824\n",
      "At step 300:\n",
      "Training Loss is 2.3025851249694824\n",
      "Training Accuracy is 0.09375\n",
      "Testing Accuracy is 0.1\n",
      "Loss is :2.3025851249694824\n",
      "At step 400:\n",
      "Training Loss is 2.3025851249694824\n",
      "Training Accuracy is 0.1875\n",
      "Testing Accuracy is 0.1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 275, in <module>\n",
      "    main()\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 260, in main\n",
      "    optimizer=optimizer, epochs=300, device=device, writer=writer)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 139, in train\n",
      "    y_probs = model.forward(train_batch.float())\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 102, in forward\n",
      "    self.a1 = F.relu(self.conv1(x))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1102, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 446, in forward\n",
      "    return self._conv_forward(input, self.weight, self.bias)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 275, in <module>\n",
      "    main()\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 260, in main\n",
      "    optimizer=optimizer, epochs=300, device=device, writer=writer)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 139, in train\n",
      "    y_probs = model.forward(train_batch.float())\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 102, in forward\n",
      "    self.a1 = F.relu(self.conv1(x))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1102, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 446, in forward\n",
      "    return self._conv_forward(input, self.weight, self.bias)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 275, in <module>\n",
      "    main()\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 260, in main\n",
      "    optimizer=optimizer, epochs=300, device=device, writer=writer)\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 139, in train\n",
      "    y_probs = model.forward(train_batch.float())\n",
      "  File \"/var/folders/1y/5q_l_qqn6m1bh4kq__rzh9t00000gn/T/ipykernel_21900/272712377.py\", line 102, in forward\n",
      "    self.a1 = F.relu(self.conv1(x))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1102, in _call_impl\n",
      "    return forward_call(*input, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 446, in forward\n",
      "    return self._conv_forward(input, self.weight, self.bias)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mitchellslapik/opt/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 28, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\n",
      "ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Created on Wed Oct 20 20:40 2020\n",
    "\n",
    "@author: Yashwanth Lagisetty\n",
    "\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import torch\n",
    "import torchvision\n",
    "from torch.utils.tensorboard import SummaryWriter\n",
    "from torch import nn, optim\n",
    "import torch.nn.functional as F\n",
    "\n",
    "\n",
    "def import_data(cifar_path, n_classes, n_train, n_test, imsize, n_channels=1):\n",
    "    \"\"\"\n",
    "    Import CIFAR10 data into train and test sets\n",
    "    :param cifar_path: Path of CIFAR10 folder\n",
    "    :param n_classes: Number of CIFAR10 classes\n",
    "    :param n_train: number of training samples per class\n",
    "    :param n_test: number of testing samples per class\n",
    "    :param imsize: size of training and testing images, default = 28\n",
    "    :param n_channels: number of image channels, default = 1\n",
    "    \"\"\"\n",
    "    Train = np.zeros((n_classes * n_train, n_channels, imsize, imsize))\n",
    "    Train_labels = np.zeros((n_classes * n_train, n_classes))\n",
    "    Test = np.zeros((n_classes * n_test, n_channels, imsize, imsize))\n",
    "    Test_labels = np.zeros((n_classes * n_test, n_classes))\n",
    "\n",
    "    train_counter = 0\n",
    "    test_counter = 0\n",
    "\n",
    "    for cifar in range(n_classes):\n",
    "        for image in range(n_train):\n",
    "            im = picturedictionary['train'][cifar] = genre[image, :, :, :]\n",
    "            #im = im.astype(float) / 255 #images are already grayscale and normalized so this is not necessary\n",
    "            Train[train_counter, :, :, :] = im\n",
    "            Train_labels[train_counter, cifar] = 1\n",
    "            train_counter += 1\n",
    "\n",
    "    for cifar in range(n_classes):\n",
    "        for image in range(n_test):\n",
    "            im = picturedictionary['test'][cifar] = genre[image, :, :, :]\n",
    "            #im = im.astype(float) / 255 #images are already grayscale and normalized so this is not necessary\n",
    "            Test[test_counter, :, :, :] = im\n",
    "            Test_labels[test_counter, cifar] = 1\n",
    "            test_counter += 1\n",
    "\n",
    "    Train = torch.from_numpy(Train)\n",
    "    Test = torch.from_numpy(Test)\n",
    "    Train_labels = torch.from_numpy(Train_labels)\n",
    "    Test_labels = torch.from_numpy(Test_labels)\n",
    "    return Train, Train_labels, Test, Test_labels\n",
    "\n",
    "\n",
    "def get_device():\n",
    "    \"\"\"\n",
    "    Function designates GPU as computational device if cuda is available else defaults to CPU\n",
    "    \"\"\"\n",
    "    if torch.cuda.is_available():\n",
    "        return torch.device('cuda')\n",
    "    else:\n",
    "        return torch.device('cpu')\n",
    "\n",
    "\n",
    "class LeNet5(nn.Module):\n",
    "    \"\"\"\n",
    "    LeNet class\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"\n",
    "        Initialize components of LeNet5\n",
    "        \"\"\"\n",
    "        super(LeNet5, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=5)\n",
    "        # Uncomment and edit following lines if customized initialization is desired\n",
    "        # torch.nn.init.kaiming_uniform_(self.conv1.weight, nonlinearity='relu')\n",
    "        # torch.nn.init.constant_(self.conv1.bias, val=0.1)\n",
    "\n",
    "        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=5)\n",
    "        # Uncomment and edit following lines if customized initialization is desired\n",
    "        # torch.nn.init.kaiming_uniform_(self.conv2.weight, nonlinearity='relu')\n",
    "        # torch.nn.init.constant_(self.conv2.bias, val=0.1)\n",
    "\n",
    "        self.FC1 = nn.Linear(in_features=4 * 4 * 64, out_features=1024)\n",
    "        # Uncomment and edit following lines if customized initialization is desired\n",
    "        # torch.nn.init.kaiming_normal_(self.FC1.weight)\n",
    "        # torch.nn.init.constant_(self.FC1.bias, val=0.1)\n",
    "\n",
    "        self.FC2 = nn.Linear(in_features=1024, out_features=10)\n",
    "        # Uncomment and edit following lines if customized initialization is desired\n",
    "        # torch.nn.init.kaiming_normal_(self.FC2.weight)\n",
    "        # torch.nn.init.constant_(self.FC2.bias, val=0.1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        \"\"\"\n",
    "        Performs Forward pass of LeNet5\n",
    "        :param x: input data\n",
    "        \"\"\"\n",
    "        self.a1 = F.relu(self.conv1(x))\n",
    "        x = F.max_pool2d(self.a1, 2)\n",
    "        self.a2 = F.relu(self.conv2(x))\n",
    "        x = F.max_pool2d(self.a2, 2)\n",
    "        x = x.view(-1, 4 * 4 * 64)\n",
    "        x = F.relu(self.FC1(x))\n",
    "        x = F.relu(self.FC2(x))\n",
    "        return F.softmax(x, dim=1)\n",
    "\n",
    "\n",
    "def train(model, X_train, y_train, X_test, y_test, lossF, optimizer, device, writer, batch_size, epochs=5):\n",
    "    \"\"\"\n",
    "    Trains model\n",
    "    :param model: model to be trained\n",
    "    :param X_train: training data\n",
    "    :param y_train: training labels\n",
    "    :param batch_size: size of training batches\n",
    "    :param lossF: pytorch loss function\n",
    "    :param optimizer: pytorch optimizer\n",
    "    :param device: device on which to do computations\n",
    "    :param epochs: number of epochs\n",
    "    :param writer: summary writer to record training analytics\n",
    "    \"\"\"\n",
    "    iter_counter = 0\n",
    "    for epoch in range(epochs):\n",
    "        samp_idx = np.arange(X_train.shape[0])\n",
    "        np.random.shuffle(samp_idx)\n",
    "        split_idx = list(range(batch_size, len(samp_idx), batch_size))\n",
    "        batches = np.array_split(samp_idx, split_idx)\n",
    "        for batch in batches:\n",
    "            train_batch = X_train[batch, :, :, :].to(device)\n",
    "            train_labels = torch.argmax(y_train[batch, :], dim=1).to(device)\n",
    "\n",
    "            # Reset gradients\n",
    "            optimizer.zero_grad()\n",
    "\n",
    "            # Predict labels and calculate loss\n",
    "            y_probs = model.forward(train_batch.float())\n",
    "            loss = lossF(y_probs, train_labels.type(torch.long))\n",
    "\n",
    "            # Perform backpropagation\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "\n",
    "            # Calculate accuracy and loss\n",
    "            _, y_preds = torch.max(y_probs, 1)\n",
    "            correct = (y_preds == train_labels.float()) * 1\n",
    "            correct = correct.type(torch.float)\n",
    "            acc = torch.mean(correct).item()\n",
    "\n",
    "            if iter_counter % 100 == 0:\n",
    "                print(\"Loss is :{}\".format(loss.item()))\n",
    "                optimizer.zero_grad()\n",
    "                test_idx = np.arange(X_test.shape[0])\n",
    "                np.random.shuffle(test_idx)\n",
    "                split_idx = list(range(batch_size, len(test_idx), batch_size))\n",
    "                test_batches = np.array_split(test_idx, split_idx)\n",
    "                num_correct = 0\n",
    "                for batch in test_batches:\n",
    "                    test_batch = X_test[batch, :, :, :].to(device)\n",
    "                    test_label = torch.argmax(y_test[batch, :], dim=1).to(device)\n",
    "\n",
    "                    y_probs = model.forward(test_batch.float())\n",
    "                    _, y_preds = torch.max(y_probs, 1)\n",
    "                    correct = (y_preds == test_label.float()) * 1\n",
    "                    correct = correct.type(torch.float)\n",
    "                    correct = torch.sum(correct).item()\n",
    "                    num_correct += correct\n",
    "                test_acc = num_correct / len(y_test)\n",
    "                writer.add_scalar(\"Acc/Test\", test_acc, iter_counter)\n",
    "                writer.add_scalar(\"Loss/Train\", loss.item(), iter_counter)\n",
    "                writer.add_scalar(\"Acc/Train\", acc, iter_counter)\n",
    "                writer.add_scalar(\"mean_W1\", torch.mean(model.conv1.weight).item(), iter_counter)\n",
    "                writer.add_scalar(\"mean_W2\", torch.mean(model.conv2.weight).item(), iter_counter)\n",
    "                writer.add_scalar(\"mean_act1\", torch.mean(model.a1).item(), iter_counter)\n",
    "                writer.add_scalar(\"mean_act2\", torch.mean(model.a2).item(), iter_counter)\n",
    "\n",
    "                print('At step {}:\\nTraining Loss is {}\\nTraining Accuracy is {}\\nTesting Accuracy is {}'.format(\n",
    "                    iter_counter, loss.item(), acc, test_acc))\n",
    "\n",
    "            iter_counter += 1\n",
    "\n",
    "\n",
    "def plot_Gabor(model, model_weights_path):\n",
    "    \"\"\"\n",
    "    Function plots the filters from the fist convolution layer\n",
    "    :param model: LeNet model\n",
    "    :param model_weights_path: path to saved model weights\n",
    "    \"\"\"\n",
    "    model.load_state_dict(torch.load(model_weights_path))\n",
    "    filters = model.conv1.weight.data.numpy()\n",
    "\n",
    "    plt.figure(figsize=(10, 10))\n",
    "    for i in range(filters.shape[0]):\n",
    "        plt.subplot(6, 6, i + 1)\n",
    "        plt.imshow(filters[i, 0, :, :], cmap='gray')\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "def activation_stats_test(model, test_images, test_labels, writer, batch_size, device, model_weights_path):\n",
    "    \"\"\"\n",
    "    Computes the statistics for trained model's activations on test images \n",
    "    :param model: LeNet Model\n",
    "    :param test_images: test set images\n",
    "    :param test_labels: test set image labels\n",
    "    :param writer: summary writer to record activations\n",
    "    :param batch_size: batch size \n",
    "    :param device: device on which to run computations\n",
    "    :param model_weights_path: path for model weights\n",
    "    \"\"\"\n",
    "    model.load_state_dict(torch.load(model_weights_path))\n",
    "    idx = np.arange(test_images.shape[0])\n",
    "    np.random.shuffle(idx)\n",
    "    split_idx = list(range(batch_size, len(idx), batch_size))\n",
    "    test_batches = np.array_split(idx, split_idx)\n",
    "    num_correct = 0\n",
    "    iter_counter = 1\n",
    "    for batch in test_batches:\n",
    "        test_batch = test_images[batch, :, :, :].to(device)\n",
    "        test_label = torch.argmax(test_labels[batch, :], dim=1).to(device)\n",
    "\n",
    "        y_probs = model.forward(test_batch.float())\n",
    "        _, y_preds = torch.max(y_probs, 1)\n",
    "        correct = (y_preds == test_label.float()) * 1\n",
    "        correct = correct.type(torch.float)\n",
    "        correct = torch.sum(correct).item()\n",
    "        num_correct += correct\n",
    "\n",
    "        writer.add_scalar(\"mean_act1\", torch.mean(model.a1).item(), iter_counter)\n",
    "        writer.add_scalar(\"mean_act2\", torch.mean(model.a2).item(), iter_counter)\n",
    "        writer.add_scalar(\"std_act1\", torch.std(model.a1).item(), iter_counter)\n",
    "        writer.add_scalar(\"std_act2\", torch.std(model.a2).item(), iter_counter)\n",
    "        writer.add_scalar(\"max_act1\", torch.max(model.a1).item(), iter_counter)\n",
    "        writer.add_scalar(\"max_act2\", torch.max(model.a2).item(), iter_counter)\n",
    "        writer.add_scalar(\"min_act1\", torch.min(model.a1).item(), iter_counter)\n",
    "        writer.add_scalar(\"min_act2\", torch.min(model.a2).item(), iter_counter)\n",
    "\n",
    "        writer.add_histogram('Conv1 Activation', model.a1, iter_counter)\n",
    "        writer.add_histogram('Conv2 Activation', model.a2, iter_counter)\n",
    "        iter_counter += 1\n",
    "    test_acc = num_correct / len(test_labels)\n",
    "    print('Test accuracy is {}'.format(test_acc))\n",
    "\n",
    "\n",
    "def main():\n",
    "\n",
    "    X_train, y_train, X_test, y_test = import_data(cifar_path='./CIFAR10/', n_classes=10, n_train=1000, n_test=100,\n",
    "                                                   imsize=28)\n",
    "    \n",
    "    writer = SummaryWriter(log_dir='')\n",
    "    device = get_device()\n",
    "    net = LeNet5()\n",
    "    net.to(device)\n",
    "\n",
    "    optimizer = optim.Adam(net.parameters(), lr=.001, weight_decay=0)\n",
    "    lossF = nn.CrossEntropyLoss()\n",
    "\n",
    "    train(model=net, X_train=X_train, y_train=y_train, X_test=X_test, y_test=y_test, batch_size=32, lossF=lossF,\n",
    "          optimizer=optimizer, epochs=300, device=device, writer=writer)\n",
    "\n",
    "    # torch.save(net.state_dict(), './model_weights/net_model')\n",
    "\n",
    "    # If Gabor filter visualization is desired uncomment following 2 lines:\n",
    "    #net.to('cpu')\n",
    "    #plot_Gabor(net, './model_weights/net_model')\n",
    "\n",
    "    # If statistics on activation layer on test images is desired uncomment following 2 lines:\n",
    "    #net.to(device)\n",
    "    #activation_stats_test(model=net, test_images=X_test, test_labels=y_test, writer=writer, batch_size=32,\n",
    "    #                       device=device, model_weights_path='./model_weights/net_model')\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81aa8bd3-9da5-4b73-b977-ee99938866fa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb4c136d-cce1-45e8-8abd-1388eb14f99a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
